# Generated by Django 4.2.10 on 2024-03-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_hastag_post_hastags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hastags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.hastag'),
        ),
    ]
